"""
Django settings for pravaah project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6r-bdf^0=y=6x5z$a3x9hx3*if90-b_165u!mvo#n1b1a^5_vn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# ── Application definition ────────────────────────────────────────────────────

INSTALLED_APPS = [
    # Django built-ins
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party packages
    'rest_framework',
    'corsheaders',
    'crispy_forms',

    # PRAVAAH apps
    'apps.accounts',
    'apps.users',
    'apps.students',
    'apps.trainers',
    'apps.programs',
    'apps.courses',
    'apps.batches',
    'apps.sessions',
    'apps.attendance',
    'apps.assessments',
    'apps.certificates',
    'apps.hostels',
    'apps.rooms',
    'apps.allocations',
    'apps.finance',
    'apps.notifications',
    'apps.reports',
    'apps.dashboard',
    'apps.api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',                          # django-cors-headers
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pravaah.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],                            # global templates folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pravaah.wsgi.application'


# ── Database ──────────────────────────────────────────────────────────────────
# Development: SQLite  |  Production: switch to MySQL block below
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ── MySQL (uncomment for production) ─────────────────────────────────────────
# DATABASES = {
#     'default': {
#         'ENGINE':   'django.db.backends.mysql',
#         'NAME':     'pravaah_db',
#         'USER':     'root',
#         'PASSWORD': 'your_password',
#         'HOST':     'localhost',
#         'PORT':     '3306',
#         'OPTIONS': {
#             'charset': 'utf8mb4',
#         },
#     }
# }


# ── Custom User Model ─────────────────────────────────────────────────────────
AUTH_USER_MODEL = 'users.User'


# ── Password validation ───────────────────────────────────────────────────────
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ── Authentication redirects ──────────────────────────────────────────────────
LOGIN_URL          = '/accounts/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/accounts/login/'


# ── Internationalization ──────────────────────────────────────────────────────
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE     = 'Asia/Kolkata'
USE_I18N      = True
USE_TZ        = True


# ── Static files (CSS, JavaScript, Images) ────────────────────────────────────
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL  = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'          # collectstatic output (production)
STATICFILES_DIRS = [BASE_DIR / 'static']        # extra static sources (development)


# ── Media files (user uploads) ────────────────────────────────────────────────

MEDIA_URL  = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ── Default primary key field type ───────────────────────────────────────────
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ── Django REST Framework ─────────────────────────────────────────────────────

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}


# ── CORS (Cross-Origin Resource Sharing) ─────────────────────────────────────
# Allow the React / Vue frontend to talk to the Django API during development.

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',   # React dev server
    'http://localhost:5173',   # Vite dev server
    'http://127.0.0.1:8000',
]

CORS_ALLOW_CREDENTIALS = True


# ── Crispy Forms ──────────────────────────────────────────────────────────────

CRISPY_TEMPLATE_PACK = 'bootstrap5'


# ── Email configuration (development: print to console) ──────────────────────

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# ── Email configuration (production: SMTP) ───────────────────────────────────
# EMAIL_BACKEND       = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST          = 'smtp.gmail.com'
# EMAIL_PORT          = 587
# EMAIL_USE_TLS       = True
# EMAIL_HOST_USER     = 'your_email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your_app_password'
# DEFAULT_FROM_EMAIL  = 'PRAVAAH <your_email@gmail.com>'


# ── Logging ───────────────────────────────────────────────────────────────────

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {module}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'pravaah.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}


# ── Session ───────────────────────────────────────────────────────────────────

SESSION_COOKIE_AGE     = 86400        # 1 day in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = False


# ── Security (enable in production) ──────────────────────────────────────────
# SECURE_HSTS_SECONDS              = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS   = True
# SECURE_SSL_REDIRECT              = True
# SESSION_COOKIE_SECURE            = True
# CSRF_COOKIE_SECURE               = True